### PR TITLE
Tic Tac Teo project

### PR DESCRIPTION
**Pull request by HADDADSOHAIB**
Third milestone: Game logic
Create classes in the lib folder and develop the logic behind the game.

### CODE REVIEW

**Comment by Anna-Myzukina** [comment]
# Status: [changes required]


### Good job with the milestone. Few steps and your project can be approved:


 * [x] No puts/print and get.chomp outside main.rb file from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/). 
screenshot 


* [x] The code should respect the single responsibility rule for methods (i.e. each method does exactly one thing) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/).
screenshot 
*  [x] Use attr_readers/attr_writers instead of attr_accessors.  That variable can be set to anything. <TODO: explain why>  from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/).
screenshot




### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*
*Happy coding * <g-emoji class="g-emoji" alias="computer" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f4bb.png">computer</g-emoji>

**Comment by HADDADSOHAIB** [comment]
Hi @Anna-Myzukina , thanks for the review.
We did the required changes. There are no more puts in the logic side, we used only attr_reader and we refactor the code to enhance the single responsibilty principle by reducing the size of some functions.

**Review by euqueme — CHANGES_REQUESTED** [review]
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hello @HADDADSOHAIB and @jabichris :balloon: :lollipop: 

### Thank you for doing the changes requested by the previous reviewer, your code looks impeccable :sparkles: and your project looks professional too there's only one thing left to validate :point_down: 

## Behaviour

* [x] The application does not exit due to invalid input - it informs player about it and asks for their move again.
 
- Your game is exiting when hitting enter whenever is asking the player for an input, let's validate it doesn't exit but just display a message for all the inputs in your game

image

### That's it, team! :raised_hands: 

### Please :pray: do the change :man_technologist: :man_technologist: and submit back for a code review when you are done :memo: 

Happy coding! :rocket: 

Any questions? ask me on slack **@ Maru** :woman_technologist: 

PROJECT STATUS: REQUESTED CHANGES :vertical_traffic_light:

**Review by mosesogwo — APPROVED** [review]
**You have done well making the requested adjustments:+1:. Your milestone is approved :heavy_check_mark:**

You can now move ahead.

**Cheers:stars:**

**Comment by HADDADSOHAIB** [comment]
@mosesogwo, @Anna-Myzukina, @euqueme thanks for the reviews :)

**Pull request merged**
