### PR TITLE
Tic Tac Teo project

### PR DESCRIPTION
**Pull request by HADDADSOHAIB**
Second milestone: User interface
Add a user interface for the tic tac toe game in the console.

### CODE REVIEW

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi Team       
#### Great Job so far, but there are a few more things required. 
### General
- [ ] Make sure that you can run your game with your executable file and play with the basic flow.



### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

**Comment by HADDADSOHAIB** [comment]
Hi @kobiyoyo, we added some logic to the interface to make it work.
All those classes will be moved to the lib folder in the next milestone.

**Comment by Anna-Myzukina** [comment]
## Hi team ! Just one thing and your project can be approved!

# Status: [changes required]

*  Basic game flow is prepared: 
screen



###  [REQUIRED] 
* game informs player if selected move is a draw move




### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*
*Happy coding * <g-emoji class="g-emoji" alias="computer" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f4bb.png">computer</g-emoji>

**Comment by HADDADSOHAIB** [comment]
Hi @Anna-Myzukina ,  I added a function that tracks if the grid is full and ends the game as a draw.

**Comment by Anna-Myzukina** [comment]
# Status: [APPROVED]


### Go ahead and merge to master.


#### Goodluck in your next project Happy coding <g-emoji class="g-emoji" alias="computer" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f4bb.png">computer</g-emoji>

**Review by Anna-Myzukina — APPROVED** [review]

**Pull request merged**
